# Базовый образ Python
FROM python:3.9-slim

# Установка зависимостей системы
RUN apt-get update && apt-get install -y \
    build-essential libsqlite3-dev && \
    rm -rf /var/lib/apt/lists/*

# Установка рабочей директории
WORKDIR /app

# Создание директории для логов
RUN mkdir -p /app/logs

# Копирование зависимостей и установка
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Копирование всего проекта
COPY . .

# Указание порта для Flask
EXPOSE 5000

# Запуск приложения
CMD ["python", "app.py"]
